### ISSUE TITLE
Loading opal using Sprockets directives causes error 

### ISSUE THREAD

**Issue by caifara** [opal/opal-rails#115] opened 2019-11-25 16:34 UTC
Using Rails 6.0.1 and opal-rails 1.1.2:

application.js contains:

```
//= require opal
Opal.require("opal")
```

JS-file renders (the page loads), but the browser gives an error:

`LoadError: cannot load such file -- corelib/random/MersenneTwister`

Converting the file to a application.js.rb solves the problem, but our project combines opal and other javascript, so we need (and would prefer) the sprockets approach.

I guess this commit is causing the problem? https://github.com/opal/opal/commit/3190eedaa5a0d76d50b80028eb0dcf7684433662

**Comment by elia** [comment] 2019-11-25 23:25
Ok, so the problem is that `corelib/random/MersenneTwister` is not being marked as loaded.

Adding `Opal.loaded(['corelib/random/MersenneTwister'])` before opal (or the opal app) is loaded fixes the problem.

[Here's a diff](https://gist.github.com/elia/04f0dc0b63af1eb0747f522c9ce8c715) on a pristine new app that has the following output:

```
> HELLO FROM OPAL APP
> 11
> 336
> 57
> 25
> 167
```

---

That said, this is a bug and the instructions on the readme should work

**Comment by caifara** [comment] 2019-11-26 09:40
Thanks! Should have asked earlier …

**Comment by hmdne** [comment] 2020-07-08 08:33
See also opal/opal#2096

**Comment by elia** [comment] 2023-01-26 08:31
Should be fixed by https://github.com/opal/opal/pull/2108

**Closed by elia** 2023-01-26 08:31 UTC
Labels: sprockets, bug
